(()=>{
  let LIVE=null,HISTORY=[],routeMode='all';
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money=(n,c='VND')=>c==='VND'?new Intl.NumberFormat('vi-VN').format(Number(n)||0)+' đ':new Intl.NumberFormat('vi-VN',{style:'currency',currency:c}).format(Number(n)||0);
  const isDirect=o=>o?.is_direct===true||Number(o?.stops)===0||(o?.slices||[]).every(s=>(s.segments||[]).length===1);
  const stopCount=o=>Number.isFinite(Number(o?.stops))?Number(o.stops):Math.max(0,...(o?.slices||[]).map(s=>(s.segments||[]).length-1));
  const firstSeg=o=>o?.slices?.[0]?.segments?.[0]||{};
  const lastSeg=o=>{const a=o?.slices?.[0]?.segments||[];return a[a.length-1]||{}};
  const time=v=>v?String(v).slice(11,16):'—';
  const duration=min=>{min=Number(min)||0;return `${Math.floor(min/60)} giờ${min%60?` ${min%60} phút`:''}`};
  const via=o=>(o?.slices?.[0]?.segments||[]).slice(0,-1).map(s=>s.destination).filter(Boolean).join(', ');
  const flightNos=o=>(o?.slices||[]).flatMap(s=>(s.segments||[]).map(x=>x.flight_number).filter(Boolean)).join(' · ');
  const routeName=id=>id==='outbound'?'Chiều đi · 19/10/2026':'Chiều về · 26/10/2026';
  const routeDesc=id=>id==='outbound'?'TP.HCM → Thượng Hải':'Bắc Kinh → TP.HCM';
  const cabinLabel=v=>String(v||'').toLowerCase()==='economy'?'Hạng phổ thông':(v||'Hạng phổ thông');
  const syncThemeUI=()=>{const dark=document.documentElement.dataset.theme==='dark',icon=dark?'#i-sun':'#i-moon',label=dark?'Chuyển sang giao diện sáng':'Chuyển sang giao diện tối';$$('[data-theme-toggle]').forEach(b=>{const use=b.querySelector('use');if(use)use.setAttribute('href',icon);b.setAttribute('aria-label',label);b.setAttribute('title',label)})};
  const setTheme=value=>{document.documentElement.dataset.theme=value;localStorage.setItem('travel-theme',value);syncThemeUI();$$('[data-theme-toggle]').forEach(b=>{b.classList.remove('theme-swap');void b.offsetWidth;b.classList.add('theme-swap')})};
  document.documentElement.dataset.theme=localStorage.getItem('travel-theme')==='dark'?'dark':'light';syncThemeUI();$$('[data-theme-toggle]').forEach(b=>b.onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
  function allOffers(){return(LIVE?.routes||[]).flatMap(r=>(r.offers||[]).map(o=>({...o,__route:r.id})))}
  function filtered(r){let a=[...(r.offers||[])],st=$('#stops').value,air=$('#airline').value,sort=$('#sort').value,q=$('#flightSearch').value.trim().toLowerCase();if(st==='direct')a=a.filter(isDirect);if(st==='one')a=a.filter(o=>stopCount(o)===1);if(air!=='all')a=a.filter(o=>o.owner?.name===air);if(q)a=a.filter(o=>`${o.owner?.name||''} ${flightNos(o)}`.toLowerCase().includes(q));a.sort((x,y)=>{if(sort==='recommended'){if(isDirect(x)!==isDirect(y))return isDirect(x)?-1:1;return Number(x.total_amount)-Number(y.total_amount)}if(sort==='price')return Number(x.total_amount)-Number(y.total_amount);if(sort==='duration')return Number(x.total_duration_minutes)-Number(y.total_duration_minutes);return String(firstSeg(x).departing_at||'').localeCompare(String(firstSeg(y).departing_at||''))});return a}
  function offerCard(o,i){const f=firstSeg(o),l=lastSeg(o),d=isDirect(o),segments=o?.slices?.[0]?.segments||[],url=o.google_flights_url||'https://www.google.com/travel/flights';const stopText=d?'Bay thẳng':`1 điểm dừng${via(o)?` · ${via(o)}`:''}`;const aircraft=[...new Set(segments.map(x=>x.airplane).filter(Boolean))].join(' · ');const travelClass=cabinLabel(segments[0]?.travel_class||LIVE?.search?.cabin_class);const foot=[flightNos(o),aircraft,travelClass,o.source].filter(Boolean);return `<article class="flight-offer ${d?'is-direct':''}" style="--row:${i}"><div class="flight-offer-main"><div class="offer-airline"><span class="offer-airline-logo">${o.owner?.logo_symbol_url?`<img src="${esc(o.owner.logo_symbol_url)}" alt="${esc(o.owner?.name||'Hãng bay')}">`:'<svg class="ui-icon" aria-hidden="true"><use href="#i-plane"/></svg>'}</span><div class="offer-airline-copy"><strong>${esc(o.owner?.name||'Hãng bay')}</strong><span>${esc(flightNos(o)||'Chuyến bay')}</span></div></div><div class="offer-flight"><div class="offer-time"><strong>${time(f.departing_at)}</strong><span>${esc(o.slices?.[0]?.origin||f.origin||'—')}</span></div><div class="offer-path"><div class="offer-duration">${duration(o.total_duration_minutes)}</div><div class="offer-line"></div><div class="offer-stop ${d?'direct':''}">${esc(stopText)}</div></div><div class="offer-time right"><strong>${time(l.arriving_at)}</strong><span>${esc(o.slices?.[0]?.destination||l.destination||'—')}</span></div></div><div class="offer-fare">${d&&i===0?'<span class="pill success offer-badge">Ưu tiên bay thẳng</span>':''}<strong>${money(o.total_amount,o.total_currency)}</strong><small>Tổng giá cho nhóm · một chiều</small><a class="btn sm" href="${esc(url)}" target="_blank" rel="noopener">Xem trên Google Flights</a></div></div><div class="offer-foot">${foot.map(x=>`<span>${esc(x)}</span>`).join('')}</div></article>`}
  function render(){if(!LIVE)return;const routes=(LIVE.routes||[]).filter(r=>routeMode==='all'||r.id===routeMode);let total=0;$('#results').innerHTML=routes.map(r=>{const a=filtered(r);total+=a.length;return `<section class="route-group"><div class="route-group-head"><div><strong>${routeName(r.id)}</strong><small>${routeDesc(r.id)}</small></div><span class="route-count">${a.length} lựa chọn</span></div>${a.length?a.map(offerCard).join(''):'<div class="offer-empty">Không có chuyến bay phù hợp với bộ lọc hiện tại.</div>'}</section>`}).join('');$('#resultMeta').textContent=`${total} lựa chọn đang hiển thị`}
  function historyRows(){const key=LIVE?.search?.trip_key;return HISTORY.filter(x=>x.trip_key===key&&x.mode==='direct-priority').map(x=>({...x,n:Number(x.total_amount)})).filter(x=>Number.isFinite(x.n)).sort((a,b)=>new Date(a.checked_at)-new Date(b.checked_at))}
  function renderChart(rows){const svg=$('#priceChart');if(!rows.length){svg.innerHTML='';$('#chartMeta').textContent='Chưa có lịch sử giá cho hành trình này.';return}const data=rows.slice(-30),vals=data.map(x=>x.n),min=Math.min(...vals),max=Math.max(...vals),rg=max-min||1,p=12,w=760,h=150;const pts=data.map((x,i)=>({x:data.length===1?w/2:p+i/(data.length-1)*(w-p*2),y:h-p-(x.n-min)/rg*(h-p*2)}));svg.innerHTML=`<line x1="0" y1="${h-p}" x2="${w}" y2="${h-p}"></line><line x1="0" y1="${p}" x2="${w}" y2="${p}"></line>${data.length>1?`<polyline points="${pts.map(x=>`${x.x},${x.y}`).join(' ')}"></polyline>`:''}${pts.map(x=>`<circle cx="${x.x}" cy="${x.y}" r="4"></circle>`).join('')}`;$('#chartMeta').textContent=`${data.length} lần cập nhật · thấp nhất ${money(min)} · cao nhất ${money(max)}`;$('#observedRange').textContent=min===max?money(min):`${money(min)} – ${money(max)}`;if(data.length>1){const cur=data.at(-1).n,pos=max===min?50:Math.max(3,Math.min(97,(cur-min)/(max-min)*100));$('#rangeMarker').hidden=false;$('#rangeMarker').style.left=`calc(${pos}% - 8px)`;$('#rangeNote').textContent=cur<=min+(max-min)*.35?'Giá hiện tại đang ở vùng thấp của lịch sử đã ghi nhận.':'Giá hiện tại chưa nằm trong vùng thấp của lịch sử đã ghi nhận.'}}
  function stats(){const all=allOffers(),direct=all.filter(isDirect).length,pair=LIVE?.cheapest?.offer;$('#pairPrice').classList.remove('loading-value');$('#directCount').classList.remove('loading-value');$('#updatedAgo').classList.remove('loading-value');$('#pairPrice').textContent=pair?money(pair.total_amount,pair.total_currency):'Chưa đủ dữ liệu';$('#pairMeta').textContent=pair?'Phương án ưu tiên ở mỗi chặng':'Một chặng chưa có giá';$('#directCount').textContent=direct;$('#directMeta').textContent=`${all.length} lựa chọn trên cả hai chặng`;const dt=new Date(LIVE?.generated_at);if(!Number.isNaN(dt.getTime())){const h=Math.max(0,Math.floor((Date.now()-dt)/3600000));$('#updatedAgo').textContent=h<1?'Dưới 1 giờ':h<24?`${h} giờ trước`:`${Math.floor(h/24)} ngày trước`;$('#updatedAt').textContent=new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(dt)}}
  function target(){const v=localStorage.getItem('flight-target')||'';if(v&&!$('#targetPrice').value)$('#targetPrice').value=v;const p=LIVE?.cheapest?.offer,box=$('#targetAlert');box.classList.remove('show');if(!p||!$('#targetPrice').value)return;const t=Number($('#targetPrice').value.replace(/\D/g,'')),c=Number(p.total_amount);if(!t)return;box.classList.add('show');box.textContent=c<=t?`Đã đạt mục tiêu: ${money(c)} ≤ ${money(t)}.`:`Hiện tại cao hơn mục tiêu ${money(c-t)}.`}
  async function load(){try{const[d,h]=await Promise.all([fetch(`./data/flights.json?t=${Date.now()}`,{cache:'no-store'}).then(r=>r.json()),fetch(`./data/flight-history.json?t=${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():[]).catch(()=>[])]);LIVE=d;HISTORY=Array.isArray(h)?h:[];const names=[...new Set(allOffers().map(o=>o.owner?.name).filter(Boolean))].sort();$('#airline').innerHTML='<option value="all">Tất cả hãng</option>'+names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');stats();render();renderChart(historyRows());target()}catch(e){$('#results').innerHTML='<div class="offer-empty">Không thể tải dữ liệu chuyến bay. Hãy thử tải lại trang.</div>';$('#resultMeta').textContent='Dữ liệu không khả dụng'}}
  $$('#routeTabs .route-tab').forEach(b=>b.onclick=()=>{$$('#routeTabs .route-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');routeMode=b.dataset.route;render()});['stops','airline','sort'].forEach(id=>$('#'+id).onchange=render);$('#flightSearch').oninput=render;$('#resetFilters').onclick=()=>{routeMode='all';$$('#routeTabs .route-tab').forEach((x,i)=>x.classList.toggle('active',i===0));$('#flightSearch').value='';$('#stops').value='all';$('#airline').value='all';$('#sort').value='recommended';render()};$('#saveTarget').onclick=()=>{const v=$('#targetPrice').value.replace(/\D/g,'');localStorage.setItem('flight-target',v);$('#targetPrice').value=v;target()};load();
})();
